sudo: required

language: generic

services:
- docker

arch:
  packages:
  - openmpi
  - cpplint
  script:
  - if ! ./test_all.sh; then exit 1; fi
  - if ! ./lint_all.sh; them exit 1; fi

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
